server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      auto-offset-reset: earliest
  rabbitmq:
    host: rabbitmq

app:
  kafka:
    topic:
      creditApplications: credit-applications
